### ISSUE TITLE
1470 - Shuffle the Array

### ISSUE THREAD

**Issue by suhridmathur** [vJechsmayr/PythonAlgorithms#739] opened 2020-10-12 06:27 UTC
## Description of the Problem
Given the array nums consisting of 2n elements in the form [x1,x2,...,xn,y1,y2,...,yn].

Return the array in the form [x1,y1,x2,y2,...,xn,yn].

## Code
```
class Solution:
    def shuffle(self, nums: List[int], n: int) -> List[int]:
        shuffled_list = [0]*(2*n)
        left_index = 0
        right_index = n
        for index in range(0, 2*n):
            if index%2 == 0:
                shuffled_list[index] = nums[left_index]
                left_index += 1
            else:
                shuffled_list[index] = nums[right_index]
                right_index += 1
        return shuffled_list
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/shuffle-the-array/)

**Comment by riwim** [comment] 2020-10-12 21:17
Duplicate of #584

**Closed as completed** 2020-10-28 08:23 UTC
Labels: hacktoberfest
