### ISSUE TITLE
0342 - Power of Four

### ISSUE THREAD

**Issue by matheusphalves** [vJechsmayr/PythonAlgorithms#607] opened 2020-10-10 16:26 UTC
## Description of the Problem
Given an integer (signed 32 bits), write a function to check whether it is a power of 4.

**Example 1:**
```
Input: 16
Output: true
```

**Example 2:**
```
Input: 5
Output: false
```

**Follow up**: Could you solve it without loops/recursion?

## Code
```
import math
class Solution:
    #Solution without loops/recursion
    def isPowerOfFour(self, num: int) -> bool:
        if(num!=0): #number 0 there isn't in the logarithmic function domain!
            exponent = math.log(abs(num), 4) #I will discover the number which multiply 4 nth times. The result must be equal to num. Ex: 4^2 = 16
            #However, the exponent must to be an integer value for num  to be a power of 4. For example, there are no 4's half number power!
            return int(math.pow(4, int(exponent)))==num
        return False #number zero was the input
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/power-of-four/)

**Comment by julienperce** [comment] 2020-10-10 16:36
Hello, could you assign this to me? Thank you.

**Comment by Curious-Ujjwal** [comment] 2020-10-10 17:49
If the issue is yet opened , can it be assigned to me?

**Comment by matheusphalves** [comment] 2020-10-10 18:40
Hi, I already solve the problem. I'm waiting for owner close this issue and the pull request linked.
Thanks for asking!

**Comment by flick-23** [comment] 2020-10-12 10:28
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)

**Closed as completed** 2020-10-28 07:49 UTC
Labels: hacktoberfest
